module.exports = {
  title: "uBlog",
  description:
    "A minimalist blog on nostr that allows anyone to easily create their own personal micro-blog.",
  favicon:
    "https://upload.wikimedia.org/wikipedia/commons/0/0b/Greek_lc_mu.svg",
  logo: "https://upload.wikimedia.org/wikipedia/commons/0/0b/Greek_lc_mu.svg",
  npub: "npub1qd3hhtge6vhwapp85q8eg03gea7ftuf9um4r8x4lh4xfy2trgvksf6dkva",
  themes: [
    // "light",
    // "dark",
    // "cupcake",
    // "bumblebee",
    // "emerald",
    // "corporate",
    // "synthwave",
    // "retro",
    // "cyberpunk",
    // "valentine",
    // "halloween",
    // "garden",
    // "forest",
    // "aqua",
    // "lofi",
    // "pastel",
    // "fantasy",
    // "wireframe",
    // "black",
    // "luxury",
    // "dracula",
    // "cmyk",
    // "autumn",
    // "business",
    // "acid",
    // "lemonade",
    // "night",
    // "coffee",
    // "winter",
  ],
  customThemes: [
    {
      custom: {
        primary: "#cba6f7",
        secondary: "#f2cdcd",
        accent: "#cba6f7",
        neutral: "#181825",
        "base-100": "#1e1e2e",
        info: "#89b4fa",
        success: "#a6e3a1",
        warning: "#f9e2af",
        error: "#f38ba8",
      },
    },
  ],
  relays: [
    "wss://relay.snort.social",
    "wss://nostr-pub.wellorder.net",
    "wss://relay.damus.io",
    "wss://nos.lol",
    "wss://nostr.wine",
    // "wss://nostr.nostrelay.org",
    // "wss://relay.nostr.ch",
    // "wss://nostr.bitcoiner.social",
    // "wss://nostr.onsats.org",
    // "wss://nostr-relay.wlvs.space",
    // "wss://nostr.zebedee.cloud",
    // "wss://relay.nostr.info",
  ],
};
